## Basic functions in python 
Functions are defined using def, arguments can be defined with out without default values.

In [3]:
def f(x, y=2, z=3):
    print(f"x={x}, y={y}, z={z}")

In [4]:
f(2)

x=2, y=2, z=3


In [3]:
f("abc", y=True)

x=abc, y=True, z=3


In [ ]:
f()

In [6]:
def f(x:int, y=2, z=3) -> int:
    print(f"x={x}, y={y}, z={z}")
    return x

In [7]:
f("abc", y=True)

x=abc, y=True, z=3


'abc'

In [9]:
f.__annotations__

{'x': int, 'return': int}

In [10]:
dir(f)

['__annotations__',
 '__builtins__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__getstate__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [11]:
f = 23

In [12]:
f 

23

In [13]:
f(2)

TypeError: 'int' object is not callable

## return statements

In [12]:
def fsquare(x) : 
    x**2

In [13]:
fsquare(2)

In [14]:
type(fsquare(2))

NoneType

In [15]:
def fsquare(x) : 
    return x**2

In [16]:
fsquare(3)

9

In [17]:
type(fsquare(3))

int

In [18]:
def is_odd(x):
    if x % 2 == 0: return False
    else:          return True
is_odd(2)

False

In [19]:
is_odd(2)

False

In [20]:
#Functions can return multiple values using a tuple or list,

def f():
    return (1,2,3)
f()


(1, 2, 3)

In [21]:
def g():
    return [1,2,3]
g()



[1, 2, 3]

In [ ]:
# What about this?
def h():
    return 1,2,3
h()


def i():
    return 1, [2, 3]
i()

## Doc strings

A common practice in Python is to document a function (and other objects) using a doc string - this is a short concise summary of the objects purpose. Doc strings are specified by supplying a string as the very line in the function definition.

In [22]:
def f():
    "Hello."
    pass


In [23]:
type(f)

function

In [24]:
dir(f)

['__annotations__',
 '__builtins__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__getstate__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [25]:
f.__name__

'f'

In [26]:
f.__doc__

'Hello.'

## Variadic arguments

If the number of arguments is unknown it is possible to define to define variadic functions



In [27]:
def paste(*args, sep=" "):
    return sep.join(args)

paste("A")


'A'

In [28]:
paste("A","B","C")

'A B C'

In [29]:
paste("1","2","3",sep=",")

'1,2,3'

In [30]:
#For the following function x can only be passed by position and z only by name

def f(x, /, y, *, z):
    print(f"x={x}, y={y}, z={z}")



In [ ]:
f(1,1,1)

f(x=1,y=1,z=1)

f(1,1,z=1)

f(1,y=1,z=1)

In [31]:
g = lambda x, y: x**2 + y**2
g(2,3)

13

In [32]:
g = lambda x,y : x**y
sign = lambda x: 1 if x > 0 else -1 if x < 0 else 0

## Function annotations (type hinting)

Python nows supports syntax for providing metadata around the expected type of arguments and the return value of a function.



In [33]:
def f(x: str, y: str, z: str) -> str:
    return x + y + z

In [34]:
f?

In [ ]:
f("A","B","C")

In [35]:
f(1,2,3)

6

In [36]:
f("A", 1, "B")

TypeError: can only concatenate str (not "int") to str

In [14]:
def f(x, /, y, *, z):
    print(f"x={x}, y={y}, z={z}")

In [16]:
f(1,y=1,z=1)

x=1, y=1, z=1


## Recursive function 
### Fibonacci series

In [17]:
def fibonacci(n) : 
    if n == 0 : 
        return n 
    elif n == 1 : 
        return n 
    else : 
        return fibonacci(n-1) + fibonacci(n-2)

In [22]:
fibonacci(45)

1134903170

## Exercise 2

Write a function, kg_to_lb, that converts a list of weights in kilograms to a list of weights in pounds (there a 1 kg = 2.20462 lbs). Include a doc string and function annotations.

Write a second function, total_lb, that calculates the total weight in pounds of an order, the input arguments should be a list of item weights in kilograms and a list of the number of each item ordered.


# Numpy

In [25]:
# importing a module in Python 
import numpy as np 

In [26]:
np.array([1,2,3])


array([1, 2, 3])

In [28]:
np.array([[1,2],[3,4]])


array([[1, 2],
       [3, 4]])

In [29]:
np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])